### ISSUE TITLE
Empty Budget List

### ISSUE THREAD

**Issue by StefTas5562** [monsieurh/homebank_android#1]
With great joy, I see that again someone cares about HomeBank for Android. Thank you Hubert.

I have been using HomeBank with LinuxMint for years and was enthusiastic from the start.
I installed the app on my LG G6 with Android 6.0 easily.
All my databases can be opened from the Google Drive and I see all Accounts.
Only the Budget List remains empty.
Whether I use my old DB or a new one. The Budget List remains empty.

What am I doing wrong?

Thank you, Stefano

**Comment by monsieurh** [comment]
Hello ! Thank your for reporting this.

I can't tell what's wrong with so little information. Do you have a budget for the current month ? Does your category names contain any weird character ? Anything special about your budget files that comes to mind ?

Also what version of homebank did you use ?

**Comment by StefTas5562** [comment]
Hi,
I use HomeBank 5.1.5 and I create a new test DB.
Attached the test DB.
Stefano
[untitled.xhb.txt](https://github.com/monsieurh/homebank_android/files/1227918/untitled.xhb.txt)

**Comment by monsieurh** [comment]
Explanation : the test DB attached has no budget.

**Comment by StefTas5562** [comment]
That was my problem.
I have never entered a budget. It works now.

But I also think that a budget value of 0 can be.

Thanks for your quick help.
Stefano
